import os
from pygame import Color

SPRITE_SIZE = 32
MAX_LEVEL_SIZE = 25

TITLE = 'ОГОНЬ и ВОДА'
SCREEN_WIDTH = MAX_LEVEL_SIZE * SPRITE_SIZE
SCREEN_HEIGHT = MAX_LEVEL_SIZE * SPRITE_SIZE

TURBO_MODE = False

FPS = 30 if not TURBO_MODE else 100
PLAYER_STEP = SPRITE_SIZE // (8 if not TURBO_MODE else 4)
PLAYER_ANIMATION_DURATION = 70 if not TURBO_MODE else 10

# Константы цветов
COLOR_BLACK = Color('black')
COLOR_WHITE = Color('white')
COLOR_RED = Color('red')
COLOR_GREEN = Color('green')
COLOR_BLUE = Color('blue')

# Константы папок и путей к ним
DIR_NAME_LEVELS = 'levels'
DIR_NAME_IMAGES = 'img'

CURRENT_DIR = os.path.dirname(__file__)
LEVELS_DIR = os.path.join(CURRENT_DIR, DIR_NAME_LEVELS)
IMG_DIR = os.path.join(CURRENT_DIR, DIR_NAME_IMAGES)

# Константы имён файлов
CSV_FILE_SAVE = "save.csv"

SPRITE_FILE_WALLS = "walls.png"
SPRITE_FILE_FLOOR = "floor.png"
SPRITE_FILE_LAVA = "lava.png"
SPRITE_FILE_RIVER = "river.png"
SPRITE_FILE_ACID = "acid.png"
SPRITE_FILE_FIRE_PLAYER = "fire_player.png"
SPRITE_FILE_WATER_PLAYER = "water_player.png"
SPRITE_FILE_ELEMENTS = "elements.png"
SPRITE_FILE_LEVEL_ICONS = "level_icons.png"

IMG_FILE_TITLE = "title.png"

# Константы обозначений блоков и элементов на уровне
LEVEL_BLOCK_EMPTY = " "
LEVEL_BLOCK_FLOOR = "."
LEVEL_BLOCK_WALL = "#"
LEVEL_BLOCK_LAVA = "L"
LEVEL_BLOCK_RIVER = "R"
LEVEL_BLOCK_ACID = "A"

LEVEL_PLAYER_FIRE = "f"
LEVEL_PLAYER_WATER = "w"

LEVEL_ELEM_RUBY = "<"
LEVEL_ELEM_AQUAMARINE = ">"
LEVEL_ELEM_FIRE_EXIT = "F"
LEVEL_ELEM_WATER_EXIT = "W"
LEVEL_ELEM_DOORBUTTON_1 = "b"
LEVEL_ELEM_DOORBUTTON_2 = "B"
LEVEL_ELEM_DOOR_1 = "d"
LEVEL_ELEM_DOOR_2 = "D"
LEVEL_ELEM_INPUT_PORTAL_1 = "i"
LEVEL_ELEM_INPUT_PORTAL_2 = "I"
LEVEL_ELEM_OUTPUT_PORTAL_1 = "o"
LEVEL_ELEM_OUTPUT_PORTAL_2 = "O"
LEVEL_ELEM_PORTAL_SWITCH_1 = "y"
LEVEL_ELEM_PORTAL_SWITCH_2 = "Y"

# Константы для цветов на начальном и конечном экранах
SCREEN_BG_COLOR1 = "bg_color1"
SCREEN_BG_COLOR2 = "bg_color2"
SCREEN_SHADOW_COLOR = "shadow_color"
SCREEN_TEXT_COLOR = "text_color"
SCREEN_FIRE_TEXT_COLOR = "fire_text_color"
SCREEN_FIRE_SHADOW_COLOR = "fire_shadow_color"
SCREEN_WATER_TEXT_COLOR = "water_text_color"
SCREEN_WATER_SHADOW_COLOR = "water_shadow_color"

SCREEN_COLORS_DICT = {
    SCREEN_BG_COLOR1: Color(47, 72, 78),
    SCREEN_BG_COLOR2: Color(54, 54, 54),
    SCREEN_SHADOW_COLOR: Color(27, 38, 50),
    SCREEN_TEXT_COLOR: Color(56, 105, 117),
    SCREEN_FIRE_TEXT_COLOR: Color(207, 50, 50),
    SCREEN_FIRE_SHADOW_COLOR: Color(143, 34, 34),
    SCREEN_WATER_TEXT_COLOR: Color(60, 188, 252),
    SCREEN_WATER_SHADOW_COLOR: Color(11, 94, 135)
}

TIME_START_GAME = 1
TIME_END_GAME = 2
TIME_FIRE_EXIT_ACTIVATION = 3
TIME_WATER_EXIT_ACTIVATION = 4

DURATION_GAME_TIME = 1
DURATION_FIRE_EXIT_ACTIVATION = 2
DURATION_WATER_EXIT_ACTIVATION = 3
